<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Track Trip · {{ $company?->name }}</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
*{box-sizing:border-box}body{margin:0;background:#f3f6fb;color:#172033;font-family:Arial,sans-serif}.shell{max-width:820px;margin:auto;padding:18px}.brand{display:flex;align-items:center;gap:12px;margin:8px 0 20px}.brand img{max-width:54px;max-height:54px}.brand strong{font-size:22px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:18px;margin-bottom:14px}.label{color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.8px}.status{text-transform:capitalize;font-size:22px;font-weight:700;margin-top:5px}#map{height:390px;border-radius:14px;background:#e2e8f0}.photo{width:64px;height:64px;border-radius:50%;object-fit:cover;float:left;margin-right:12px}.meta{color:#475569;line-height:1.6}.stale{color:#b45309}@media(max-width:620px){.grid{grid-template-columns:1fr}#map{height:330px}}
</style></head><body><main class="shell"><div class="brand">@if($company?->logo)<img src="{{ $company->logo }}" alt="Logo">@endif <strong>{{ $company?->name ?? config('app.name') }}</strong></div><div class="grid"><section class="card"><div class="label">Booking #{{ $booking->id }}</div><div id="status" class="status">{{ str_replace('_',' ',$booking->status) }}</div><div id="updated" class="meta">Waiting for location…</div></section><section class="card" id="details"><div class="label">Driver and vehicle</div></section></div><div id="map"></div></main><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script src="https://cdn.jsdelivr.net/npm/pusher-js@8.4.0/dist/web/pusher.min.js"></script><script>
const token=@json($token),channelKey=@json($channelKey),reverbKey=@json($reverbKey),api='/api/public/trip-tracking/'+encodeURIComponent(token);let map=null,marker=null;
function showLocation(location){if(!location)return;const point=[Number(location.latitude),Number(location.longitude)];if(!map){map=L.map('map').setView(point,15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);marker=L.marker(point).addTo(map)}else{marker.setLatLng(point);map.panTo(point)}const updated=location.recorded_at?new Date(location.recorded_at):new Date();const stale=Date.now()-updated.getTime()>120000;document.getElementById('updated').className='meta'+(stale?' stale':'');document.getElementById('updated').textContent=(stale?'Last known location · ':'Location updated · ')+updated.toLocaleTimeString()}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[character]))}
function render(data){document.getElementById('status').textContent=String(data.status||'').replaceAll('_',' ');const d=data.driver||{},v=data.vehicle||{};document.getElementById('details').innerHTML='<div class="label">Driver and vehicle</div>'+(d.photo?'<img class="photo" src="'+escapeHtml(d.photo)+'" alt="Driver">':'')+'<div class="meta"><strong>'+escapeHtml(d.name||'Driver assigned')+'</strong><br>'+escapeHtml(d.phone||'')+'<br><strong>'+escapeHtml(v.name||'Vehicle pending')+'</strong><br>'+escapeHtml([v.color,v.model,v.plate_number].filter(Boolean).join(' · '))+'</div><div style="clear:both"></div>';showLocation(data.location)}
async function load(){const response=await fetch(api,{headers:{Accept:'application/json'}});if(response.ok)render((await response.json()).data)}load();setInterval(load,10000);
try{const pusher=new Pusher(reverbKey,{wsHost:location.hostname,wsPort:location.port||80,wssPort:location.port||443,wsPath:'/ws',forceTLS:location.protocol==='https:',enabledTransports:['ws','wss'],disableStats:true,cluster:'mt1'});pusher.subscribe('trip.'+channelKey).bind('booking.location.updated',event=>showLocation(event.location||event))}catch(error){}
</script></body></html>
