<!DOCTYPE html>
<html lang="en"><body style="margin:0;padding:0;background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;color:#18181b;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:24px 12px;"><tr><td align="center"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#ffffff;border:1px solid #e5e7eb;border-radius:14px;overflow:hidden;">
<tr><td style="padding:24px;background:#000;color:#fff;">@if ($booking->company?->logo)<img src="{{ $booking->company->logo }}" alt="{{ $booking->company?->name }} logo" style="max-height:44px;display:block;margin-bottom:12px;">@endif<div style="font-size:18px;font-weight:700;margin-bottom:14px;">{{ $booking->company?->name ?? config('app.name') }}</div><div style="font-size:12px;letter-spacing:1px;text-transform:uppercase;opacity:.85;">{{ $isAdminCopy ? 'Operations notification' : 'Booking cancellation confirmed' }}</div><div style="font-size:28px;font-weight:700;line-height:1.3;">{{ $isAdminCopy ? 'A customer cancelled a booking' : 'Your reservation has been cancelled' }}</div></td></tr>
<tr><td style="padding:26px 24px;"><p style="margin:0 0 12px;font-size:16px;">Hi {{ $isAdminCopy ? 'Operations team' : ($booking->name ?: $booking->customer?->name ?: 'there') }},</p><p style="margin:0 0 18px;line-height:1.6;color:#4b5563;">@if ($isAdminCopy) The customer cancelled this reservation through Manage Reservation. @else Your cancellation request has been accepted. @endif</p>
<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px 16px;margin-bottom:16px;"><div style="font-size:12px;text-transform:uppercase;letter-spacing:.8px;color:#64748b;margin-bottom:6px;">Booking reference</div><div style="font-size:20px;font-weight:700;color:#0f172a;">#{{ $booking->id }}</div></div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;"><tr><td style="padding:10px 0;border-bottom:1px solid #e5e7eb;color:#64748b;font-size:13px;width:38%;">Previous status</td><td style="padding:10px 0;border-bottom:1px solid #e5e7eb;font-weight:600;">{{ ucwords(str_replace('_', ' ', $previousStatus)) }}</td></tr><tr><td style="padding:10px 0;border-bottom:1px solid #e5e7eb;color:#64748b;font-size:13px;">Pickup</td><td style="padding:10px 0;border-bottom:1px solid #e5e7eb;font-weight:600;">{{ $booking->pickup_address }}</td></tr><tr><td style="padding:10px 0;border-bottom:1px solid #e5e7eb;color:#64748b;font-size:13px;">Pickup time</td><td style="padding:10px 0;border-bottom:1px solid #e5e7eb;font-weight:600;">{{ \Carbon\Carbon::parse($booking->pickup_time)->format('D, d M Y \a\t h:i A') }}</td></tr>@if ($isAdminCopy)<tr><td style="padding:10px 0;color:#64748b;font-size:13px;">Customer</td><td style="padding:10px 0;font-weight:600;">{{ $booking->name ?: $booking->customer?->name ?: 'Not provided' }} · {{ $booking->email ?: $booking->customer?->email ?: 'No email' }}</td></tr>@endif</table>
<p style="margin:20px 0 0;color:#374151;">Thanks,<br><strong>{{ $booking->company?->name ?? config('app.name', 'Moover') }}</strong></p></td></tr>
</table></td></tr></table></body></html>
